with payload as (
  select
    $$[
      {
        "scientific_name": "Zoanthus spp.",
        "common_name": "Zoanthids (Zoas)",
        "type": "Soft",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 420,
        "max_calcio_ppm": 440,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Medium",
        "reef_safe": "Yes",
        "care_level": "Easy"
      },
      {
        "scientific_name": "Palythoa spp.",
        "common_name": "Palythoas",
        "type": "Soft",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 420,
        "max_calcio_ppm": 440,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Medium",
        "reef_safe": "Yes",
        "care_level": "Easy"
      },
      {
        "scientific_name": "Corallimorpharia spp.",
        "common_name": "Mushroom Corals",
        "type": "Soft",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 420,
        "max_calcio_ppm": 440,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Low",
        "flow_requirement": "Low",
        "reef_safe": "Yes",
        "care_level": "Easy"
      },
      {
        "scientific_name": "Ricordea florida",
        "common_name": "Ricordea (Florida)",
        "type": "Soft",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 420,
        "max_calcio_ppm": 440,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Low",
        "reef_safe": "Yes",
        "care_level": "Easy"
      },
      {
        "scientific_name": "Ricordea yuma",
        "common_name": "Ricordea (Yuma)",
        "type": "Soft",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 420,
        "max_calcio_ppm": 440,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Low",
        "reef_safe": "Yes",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Sarcophyton spp.",
        "common_name": "Leather Coral (Toadstool)",
        "type": "Soft",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 420,
        "max_calcio_ppm": 440,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Medium",
        "reef_safe": "Yes",
        "care_level": "Easy"
      },
      {
        "scientific_name": "Sinularia spp.",
        "common_name": "Leather Coral (Sinularia)",
        "type": "Soft",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 420,
        "max_calcio_ppm": 440,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Medium",
        "reef_safe": "Yes",
        "care_level": "Easy"
      },
      {
        "scientific_name": "Cladiella spp.",
        "common_name": "Colt Coral",
        "type": "Soft",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 420,
        "max_calcio_ppm": 440,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Medium",
        "reef_safe": "Yes",
        "care_level": "Easy"
      },
      {
        "scientific_name": "Xenia spp.",
        "common_name": "Pulsing Xenia",
        "type": "Soft",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 420,
        "max_calcio_ppm": 440,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Medium",
        "reef_safe": "Yes",
        "care_level": "Easy"
      },
      {
        "scientific_name": "Anthelia spp.",
        "common_name": "Anthelia",
        "type": "Soft",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 420,
        "max_calcio_ppm": 440,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Medium",
        "reef_safe": "Yes",
        "care_level": "Easy"
      },
      {
        "scientific_name": "Capnella spp.",
        "common_name": "Kenya Tree Coral",
        "type": "Soft",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 420,
        "max_calcio_ppm": 440,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Medium",
        "reef_safe": "Yes",
        "care_level": "Easy"
      },
      {
        "scientific_name": "Clavularia spp.",
        "common_name": "Green Star Polyps / Clavularia",
        "type": "Soft",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 420,
        "max_calcio_ppm": 440,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "High",
        "reef_safe": "Yes",
        "care_level": "Easy"
      },
      {
        "scientific_name": "Tubipora musica",
        "common_name": "Pipe Organ Coral",
        "type": "Soft",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 420,
        "max_calcio_ppm": 440,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "High",
        "reef_safe": "Yes",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Euphyllia spp.",
        "common_name": "Euphyllia (Hammer / Torch / Frogspawn)",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Medium",
        "reef_safe": "With Caution",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Favia spp.",
        "common_name": "Favia Brain Coral",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Low",
        "reef_safe": "With Caution",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Favites spp.",
        "common_name": "Favites Brain Coral",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Low",
        "reef_safe": "With Caution",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Lobophyllia spp.",
        "common_name": "Lobo Brain Coral",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Low",
        "flow_requirement": "Low",
        "reef_safe": "With Caution",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Trachyphyllia geoffroyi",
        "common_name": "Open Brain Coral (Trachyphyllia)",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Low",
        "flow_requirement": "Low",
        "reef_safe": "With Caution",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Micromussa lordhowensis",
        "common_name": "Acan Lord (Micromussa)",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Low",
        "flow_requirement": "Low",
        "reef_safe": "With Caution",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Acanthastrea spp.",
        "common_name": "Acanthastrea (Acans)",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Low",
        "flow_requirement": "Low",
        "reef_safe": "With Caution",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Blastomussa wellsi",
        "common_name": "Blastomussa wellsi",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Low",
        "flow_requirement": "Low",
        "reef_safe": "With Caution",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Fungia spp.",
        "common_name": "Plate Coral (Fungia)",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Low",
        "flow_requirement": "Low",
        "reef_safe": "With Caution",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Scolymia spp.",
        "common_name": "Scolymia",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Low",
        "flow_requirement": "Low",
        "reef_safe": "With Caution",
        "care_level": "Expert"
      },
      {
        "scientific_name": "Goniopora spp.",
        "common_name": "Goniopora (Flowerpot Coral)",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Medium",
        "reef_safe": "Yes",
        "care_level": "Expert"
      },
      {
        "scientific_name": "Alveopora spp.",
        "common_name": "Alveopora",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Medium",
        "reef_safe": "Yes",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Caulastrea spp.",
        "common_name": "Candy Cane Coral (Trumpet Coral)",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Low",
        "reef_safe": "Yes",
        "care_level": "Easy"
      },
      {
        "scientific_name": "Duncanopsammia axifuga",
        "common_name": "Duncan Coral",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Medium",
        "reef_safe": "Yes",
        "care_level": "Easy"
      },
      {
        "scientific_name": "Echinophyllia spp.",
        "common_name": "Chalice Coral",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Low",
        "flow_requirement": "Low",
        "reef_safe": "With Caution",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Catalaphyllia jardinei",
        "common_name": "Elegance Coral",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Low",
        "reef_safe": "With Caution",
        "care_level": "Expert"
      },
      {
        "scientific_name": "Nemenzophyllia turbida",
        "common_name": "Fox Coral",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Low",
        "reef_safe": "With Caution",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Galaxea fascicularis",
        "common_name": "Galaxea Coral",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Medium",
        "reef_safe": "With Caution",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Cyphastrea spp.",
        "common_name": "Cyphastrea",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Medium",
        "reef_safe": "Yes",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Leptastrea spp.",
        "common_name": "Leptastrea",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Medium",
        "reef_safe": "Yes",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Turbinaria spp.",
        "common_name": "Turbinaria Coral",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "High",
        "reef_safe": "Yes",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Acropora spp.",
        "common_name": "Acropora",
        "type": "SPS",
        "min_temp_c": 24.0,
        "max_temp_c": 26.5,
        "min_sg": 1.025,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 9.5,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1280,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "High",
        "flow_requirement": "High",
        "reef_safe": "Yes",
        "care_level": "Expert"
      },
      {
        "scientific_name": "Montipora spp.",
        "common_name": "Montipora",
        "type": "SPS",
        "min_temp_c": 24.0,
        "max_temp_c": 26.5,
        "min_sg": 1.025,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 9.5,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1280,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "High",
        "flow_requirement": "High",
        "reef_safe": "Yes",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Seriatopora hystrix",
        "common_name": "Birdsnest Coral",
        "type": "SPS",
        "min_temp_c": 24.0,
        "max_temp_c": 26.5,
        "min_sg": 1.025,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 9.5,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1280,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "High",
        "flow_requirement": "High",
        "reef_safe": "Yes",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Pocillopora damicornis",
        "common_name": "Pocillopora",
        "type": "SPS",
        "min_temp_c": 24.0,
        "max_temp_c": 26.5,
        "min_sg": 1.025,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 9.5,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1280,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "High",
        "flow_requirement": "High",
        "reef_safe": "Yes",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Stylophora pistillata",
        "common_name": "Stylophora",
        "type": "SPS",
        "min_temp_c": 24.0,
        "max_temp_c": 26.5,
        "min_sg": 1.025,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 9.5,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1280,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "High",
        "flow_requirement": "High",
        "reef_safe": "Yes",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Leptoseris spp.",
        "common_name": "Leptoseris (Encrusting/Plating)",
        "type": "SPS",
        "min_temp_c": 24.0,
        "max_temp_c": 26.5,
        "min_sg": 1.025,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 9.5,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1280,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Medium",
        "reef_safe": "Yes",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Psammocora spp.",
        "common_name": "Psammocora",
        "type": "SPS",
        "min_temp_c": 24.0,
        "max_temp_c": 26.5,
        "min_sg": 1.025,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 9.5,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1280,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Medium",
        "reef_safe": "Yes",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Stylocoeniella spp.",
        "common_name": "Stylocoeniella",
        "type": "SPS",
        "min_temp_c": 24.0,
        "max_temp_c": 26.5,
        "min_sg": 1.025,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 9.5,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1280,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Medium",
        "reef_safe": "Yes",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Pavona cactus",
        "common_name": "Pavona Cactus Coral",
        "type": "SPS",
        "min_temp_c": 24.0,
        "max_temp_c": 26.5,
        "min_sg": 1.025,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 9.5,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1280,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "High",
        "flow_requirement": "High",
        "reef_safe": "With Caution",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Millepora spp.",
        "common_name": "Fire Coral (Millepora)",
        "type": "SPS",
        "min_temp_c": 24.0,
        "max_temp_c": 26.5,
        "min_sg": 1.025,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 9.5,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1280,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "High",
        "flow_requirement": "High",
        "reef_safe": "With Caution",
        "care_level": "Expert"
      },
      {
        "scientific_name": "Hydnophora spp.",
        "common_name": "Hydnophora (Horn Coral)",
        "type": "SPS",
        "min_temp_c": 24.0,
        "max_temp_c": 26.5,
        "min_sg": 1.025,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 9.5,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1280,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "High",
        "flow_requirement": "High",
        "reef_safe": "With Caution",
        "care_level": "Expert"
      },
      {
        "scientific_name": "Porites spp.",
        "common_name": "Porites",
        "type": "SPS",
        "min_temp_c": 24.0,
        "max_temp_c": 26.5,
        "min_sg": 1.025,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 9.5,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1280,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "High",
        "flow_requirement": "High",
        "reef_safe": "Yes",
        "care_level": "Expert"
      },
      {
        "scientific_name": "Tubastraea spp.",
        "common_name": "Sun Coral (Tubastrea)",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Low",
        "flow_requirement": "Medium",
        "reef_safe": "Yes",
        "care_level": "Expert"
      },
      {
        "scientific_name": "Dendronephthya spp.",
        "common_name": "Dendronephthya (NPS Soft Coral)",
        "type": "Soft",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 420,
        "max_calcio_ppm": 440,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Low",
        "flow_requirement": "High",
        "reef_safe": "Yes",
        "care_level": "Expert"
      },
      {
        "scientific_name": "Pseudopterogorgia spp.",
        "common_name": "Photosynthetic Gorgonian",
        "type": "Soft",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 420,
        "max_calcio_ppm": 440,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "High",
        "flow_requirement": "High",
        "reef_safe": "Yes",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Diodogorgia nodulifera",
        "common_name": "Non-Photosynthetic Gorgonian (Diodogorgia)",
        "type": "Soft",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 420,
        "max_calcio_ppm": 440,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Low",
        "flow_requirement": "High",
        "reef_safe": "Yes",
        "care_level": "Expert"
      },
      {
        "scientific_name": "Turbinaria peltata",
        "common_name": "Pagoda Cup Coral",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Medium",
        "reef_safe": "Yes",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Pectinia spp.",
        "common_name": "Pectinia (Space Invader)",
        "type": "LPS",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 400,
        "max_calcio_ppm": 450,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "Medium",
        "flow_requirement": "Low",
        "reef_safe": "With Caution",
        "care_level": "Expert"
      },
      {
        "scientific_name": "Entacmaea quadricolor",
        "common_name": "Bubble Tip Anemone (BTA)",
        "type": "Anemone",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 420,
        "max_calcio_ppm": 440,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "High",
        "flow_requirement": "Medium",
        "reef_safe": "With Caution",
        "care_level": "Moderate"
      },
      {
        "scientific_name": "Macrodactyla doreensis",
        "common_name": "Long Tentacle Anemone (LTA)",
        "type": "Anemone",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 420,
        "max_calcio_ppm": 440,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "High",
        "flow_requirement": "Medium",
        "reef_safe": "With Caution",
        "care_level": "Expert"
      },
      {
        "scientific_name": "Stichodactyla haddoni",
        "common_name": "Carpet Anemone",
        "type": "Anemone",
        "min_temp_c": 24.0,
        "max_temp_c": 27.0,
        "min_sg": 1.024,
        "max_sg": 1.026,
        "min_dkh": 8.0,
        "max_dkh": 10.0,
        "min_calcio_ppm": 420,
        "max_calcio_ppm": 440,
        "min_magnesio_ppm": 1250,
        "max_magnesio_ppm": 1350,
        "lighting_requirement": "High",
        "flow_requirement": "Medium",
        "reef_safe": "With Caution",
        "care_level": "Expert"
      }
    ]$$::jsonb as j
),
rows as (
  select
    r.scientific_name,
    r.common_name,
    r.type,
    r.min_temp_c,
    r.max_temp_c,
    r.min_sg,
    r.max_sg,
    r.min_dkh,
    r.max_dkh,
    r.min_calcio_ppm,
    r.max_calcio_ppm,
    r.min_magnesio_ppm,
    r.max_magnesio_ppm,
    r.lighting_requirement,
    r.flow_requirement,
    r.reef_safe,
    r.care_level
  from payload
  cross join lateral jsonb_to_recordset(payload.j) as r(
    scientific_name text,
    common_name text,
    type text,
    min_temp_c double precision,
    max_temp_c double precision,
    min_sg double precision,
    max_sg double precision,
    min_dkh double precision,
    max_dkh double precision,
    min_calcio_ppm double precision,
    max_calcio_ppm double precision,
    min_magnesio_ppm double precision,
    max_magnesio_ppm double precision,
    lighting_requirement text,
    flow_requirement text,
    reef_safe text,
    care_level text
  )
)
insert into public.bio_requirements (
  scientific_name,
  common_name,
  group_name,
  water_conditions,
  reef_compatible,
  lighting,
  flow,
  temp_min_c,
  temp_max_c,
  sg_min,
  sg_max,
  dkh_min,
  dkh_max,
  source,
  source_url,
  scraped_at
)
select
  scientific_name,
  coalesce(common_name, ''),
  coalesce(type, ''),
  jsonb_strip_nulls(
    jsonb_build_object(
      'min_calcio_ppm', min_calcio_ppm,
      'max_calcio_ppm', max_calcio_ppm,
      'min_magnesio_ppm', min_magnesio_ppm,
      'max_magnesio_ppm', max_magnesio_ppm,
      'care_level', care_level
    )
  )::text,
  coalesce(reef_safe, ''),
  coalesce(lighting_requirement, ''),
  coalesce(flow_requirement, ''),
  min_temp_c,
  max_temp_c,
  min_sg,
  max_sg,
  min_dkh,
  max_dkh,
  'chat_seed',
  '',
  now()
from rows
on conflict (scientific_name) do update set
  common_name = excluded.common_name,
  group_name = excluded.group_name,
  water_conditions = excluded.water_conditions,
  reef_compatible = excluded.reef_compatible,
  lighting = excluded.lighting,
  flow = excluded.flow,
  temp_min_c = excluded.temp_min_c,
  temp_max_c = excluded.temp_max_c,
  sg_min = excluded.sg_min,
  sg_max = excluded.sg_max,
  dkh_min = excluded.dkh_min,
  dkh_max = excluded.dkh_max,
  source = excluded.source,
  source_url = excluded.source_url,
  scraped_at = excluded.scraped_at,
  updated_at = now();
