insert into public.bio_requirements (
  scientific_name,
  common_name,
  group_name,
  water_conditions,
  reef_compatible,
  lighting,
  flow,
  temp_min_c,
  temp_max_c,
  sg_min,
  sg_max,
  ph_min,
  ph_max,
  dkh_min,
  dkh_max,
  source,
  source_url,
  scraped_at
)
values
  (
    'Euphyllia glabrescens',
    'Torch Coral',
    'LPS Coral',
    '72-78° F, dKH 8-12, pH 8.1-8.4, sg 1.023-1.025',
    'Yes',
    'Moderate',
    'Medium',
    22.2,
    25.6,
    1.023,
    1.025,
    8.1,
    8.4,
    8,
    12,
    'liveaquaria',
    'https://m.liveaquaria.com/product/509?pcatid=509',
    now()
  ),
  (
    'Goniopora spp.',
    'Flower Pot Coral',
    'LPS Coral',
    '72-78° F, dKH 8-12, pH 8.1-8.4, sg 1.023-1.025',
    'Yes',
    'Moderate',
    'Medium',
    22.2,
    25.6,
    1.023,
    1.025,
    8.1,
    8.4,
    8,
    12,
    'liveaquaria',
    'https://m.liveaquaria.com/product/464/',
    now()
  ),
  (
    'Alveopora spp.',
    'Alveopora Coral',
    'LPS Coral',
    null,
    null,
    'Low to Moderate',
    'Low',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'liveaquaria',
    'https://www.liveaquaria.com/product/8170/?pcatid=8170',
    now()
  ),
  (
    'Thor amboinensis',
    'Sexy Anemone Shrimp',
    'Invertebrate',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'liveaquaria',
    'https://m.liveaquaria.com/product/1135/?pcatid=1135',
    now()
  ),
  (
    'Amphiprion percula',
    'Percula Clownfish',
    'Clownfish',
    'sg 1.020-1.025, 72-78° F, dKH 8-12, pH 8.1-8.4',
    'Yes',
    null,
    null,
    22.2,
    25.6,
    1.020,
    1.025,
    8.1,
    8.4,
    8,
    12,
    'liveaquaria',
    'https://www.liveaquaria.com/product/7187/?pcatid=7187',
    now()
  )
on conflict (scientific_name) do update
set
  common_name = excluded.common_name,
  group_name = excluded.group_name,
  water_conditions = excluded.water_conditions,
  reef_compatible = excluded.reef_compatible,
  lighting = excluded.lighting,
  flow = excluded.flow,
  temp_min_c = excluded.temp_min_c,
  temp_max_c = excluded.temp_max_c,
  sg_min = excluded.sg_min,
  sg_max = excluded.sg_max,
  ph_min = excluded.ph_min,
  ph_max = excluded.ph_max,
  dkh_min = excluded.dkh_min,
  dkh_max = excluded.dkh_max,
  source = excluded.source,
  source_url = excluded.source_url,
  scraped_at = excluded.scraped_at,
  updated_at = now();
